### ISSUE TITLE
Linux embedded related: unable to get local issuer certificate

### ISSUE THREAD

**Issue by markus-fischbacher** [jeremydumais/CPP-SMTPClient-library#11]
I've written a program which runs on an i.MX6 ARM system.
The system is built using Yocto system.
If I try to send an email, I'm getting the following output:

```
c: Trying to connect to smtp.office365.com on port 587
s: 220 VI1PR04CA0137.outlook.office365.com Microsoft ESMTP MAIL Service ready at Tue, 26 Apr 2022 22:14:55 +0000
c: Connected!
c: ehlo localhost\r\n
s: 250-VI1PR04CA0137.outlook.office365.com Hello [83.215.196.27]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8
c: Info: STARTTLS is available by the server, the communication will be encrypted.
c: STARTTLS\r\n
s: 220 2.0.0 SMTP server ready
c: <Start TLS negotiation>
c & s: <Negotiate a TLS session>
c & s: <Check result of negotiation>
s: unable to get local issuer certificate
Unable to verify the result of chain verification|-58
```

I'm using the OpportunisticSecureSMTPClient client.

Do you have an idea, what's missing on my Linux distribution?
The same program compiled for Ubuntu Linux or MacOS is working properly.
There are certificates missing, but which ones?

Any help is appreciated.

Markus

**Comment by jeremydumais** [comment]
Hi Markus,

I had a similar issue with macOS Catalina as I needed to export Systems Roots certificates from the Keychain Access. This may not be exactly the same issue, but I think it's worth trying at least with the environment variables to tell OpenSSL where the CA certificates are located on the computer.

See the detail here : https://github.com/jeremydumais/CPP-SMTPClient-library/issues/9#issuecomment-1019626080

I will continue to investigate on my side.

Regards,
Jeremy

**Comment by markus-fischbacher** [comment]
Hi Jeremy,

thanks for that hin. I'll give it a shot.
BTW: thanks for that awesome library :)
It's really easy to use and working out of the box on my other systems.

Kind regards,
Markus

**Comment by markus-fischbacher** [comment]
Good hint!
Just added an environment variable and it worked.

`export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt`

Thanks Jeremy!

Kind regards,
Markus

**Comment by jeremydumais** [comment]
Thanks for the kind words Markus and for the follow up. I will add the solution on the wiki for future cases.

Regards,
Jeremy
