### ISSUE TITLE
Communication log buffer size

### ISSUE THREAD

**Issue by interfector18** [jeremydumais/CPP-SMTPClient-library#12]
There is currently and issue where sending a large message (styled html) causes the communication log to overflow. 

I've gotten `corrupted size vs. prev_size` as error output, indicating overflow in a separate thread.
Setting a bigger buffer size fixes the issue.

May I also ask why are pointers used so much and have you thought about refactoring to use more of `std::string` or `std::string_view`?

**Comment by jeremydumais** [comment]
Working on an auto-growing communication log buffer in version 1.1.5

Regarding all the pointers in class headers, the goal was to expose only Pure C Interfaces publicly. This way you have the possibility to build the library alone and consume it in many projects without having to worry about the version of the compiler and the version of the standard library used.  

This is well explained in the following blog post:                                                                  
[The Perils of C++ Interface DLLs](https://blogs.msmvps.com/gdicanio/2016/07/11/the-perils-of-c-interface-dlls/)

That being said, I think it's possible to do both. I will think of a way to let the developer choose between Pure C Interfaces or Modern C++ Interfaces.

Thanks for submitting the issue and for this excellent suggestion.

**Comment by jeremydumais** [comment]
Solved in version 1.1.5
