### ISSUE TITLE
Attachment

### ISSUE THREAD

**Issue by hesa2020** [jeremydumais/CPP-SMTPClient-library#16]
How can I get the cid (Content-ID) for an attachment in order to use an img html tag like <img src="cid:{CID HERE}"/> ?

https://www.rfc-editor.org/rfc/rfc2392 (Page 4)

I think attachment.cpp should generate a valid id and have a function to get that content id.

And then we just need to output it here: https://github.com/hesa2020/CPP-SMTPClient-library/blob/master/src/smtpclientbase.cpp#L884

Edit: I made a pull-request, I am going to handle the content-id generation on my side.

Example generation:
```
#include <iostream>
#include <string>
#include <ctime>
#include <sstream>

std::string generate_content_id() {
    std::stringstream ss;
    ss << "<" << std::time(nullptr) << "." << std::rand() << "@example.com>";
    return ss.str();
}

int main() {
    std::cout << generate_content_id() << std::endl;
    return 0;
}
```

**Comment by jeremydumais** [comment]
Hello, really good idea! I will review the pull request and merge it in the next days.
Thanks for the collaboration!

**Comment by jeremydumais** [comment]
Pull request merged. Thanks for your contribution!
