### ISSUE TITLE
Batch email sending

### ISSUE THREAD

**Issue by mlenox-bsi** [jeremydumais/CPP-SMTPClient-library#18]
For performance reasons it is often better to keep the smtp connection open if you intend to send many different emails sequentially to avoid the overhead of reconnecting with each send. Use case is emails are only sent at certain times of day and are queue up until that time.

Would be nice if sendmail() didn't close the connection after sending, but just wait until the destructor calls cleanup(). I might give it a try at some point and make a PR.

**Comment by jeremydumais** [comment]
That's a good idea. I will look at this in the next release! Thanks!

**Comment by jeremydumais** [comment]
This will be release in a few days with version 1.1.7.
