### ISSUE TITLE
Library makes assumption that unsecured connection would never use authentication

### ISSUE THREAD

**Issue by ino-josh** [jeremydumais/CPP-SMTPClient-library#22]
I ran into this issue pretty quickly with my first test email.
It _is_ possible for a server to require authentication, even if implicit TLS or STARTTLS is not used.
I would suggest that the client check for `250-AUTH` from the server and use the credentials set by the user of the library regardless of port, TLS, STARTTLS, etc.

**Comment by jeremydumais** [comment]
This is part of version 1.1.7.
