### ISSUE TITLE
First "MAIL FROM" format tried is not the standard format

### ISSUE THREAD

**Issue by ino-josh** [jeremydumais/CPP-SMTPClient-library#23]
In RFC2821, the MAIL FROM should be formatted like so:
`MAIL FROM:<Smith@bar.com>`
This library tries 3 different formats, the first of which does not match the standard.
Some servers will reject the formatting, and the response code _will not_ be `501`, which is the code checked in order to continue to check the other formats.
I would suggest that the first format tried be the de-facto standard correct format, rather than the order it is currently in.
For reference: tested with hMailServer (it returns `550 Invalid syntax. Syntax should be MAIL FROM:<mailbox@domain>[crlf]`)

**Comment by jeremydumais** [comment]
This will be release in a few days with version 1.1.7.
