### ISSUE TITLE
Add option for explicitly allowing self-signed certificates

### ISSUE THREAD

**Issue by ino-josh** [jeremydumais/CPP-SMTPClient-library#24]
For the secure and opportunistic clients, it would be ideal to be able to configure it to ignore the openssl `self-signed certificate` failure of `SSL_get_verify_result`.
The default behavior would of course be to fail at that point, but even if just for testing purposes (with a local test SMTP server), being able to ignore that error would help a lot.

**Comment by jeremydumais** [comment]
This will be release soon with version 1.1.7.

**Comment by ino-josh** [comment]
Nice.
I have [some other commits](https://github.com/Inovonics-Broadcast/CPP-SMTPClient-library/tree/fixes) that you may or may not want to look at.

**Comment by jeremydumais** [comment]
Also integrated! Thank you @ino-josh
