### ISSUE TITLE
Gmail - Multirecipients

### ISSUE THREAD

**Issue by cckang** [jeremydumais/CPP-SMTPClient-library#29]
Hi @jeremydumais , i encounter an issue when i send the email with multiple recipients using Gmail service.

Error i encounter: 

s: 550-5.7.1 This message is not RFC 5322 compliant. There are multiple To headers.
550-5.7.1 To reduce the amount of spam sent to Gmail, this message has been
550-5.7.1 blocked. For more information, go to
550-5.7.1  https://support.google.com/mail/?p=RfcMessageNonCompliant and review
550 5.7.1 RFC 5322 specifications. g14-20020a62f94e000000b006f2d97c3e87sm2449378pfm.125 - gsmtp

From google help page:
[https://support.google.com/a/answer/13567860?hl=en#zippy=%2Cduplicate-header-example-picture](url)

![image](https://github.com/jeremydumais/CPP-SMTPClient-library/assets/3318709/04899ceb-ef6d-4a5d-8fe3-f78b7d150e5f)

Any recommendation or suggestion on this?

**Comment by cckang** [comment]
communication log related to To field:

: AUTH PLAIN ***************\r\n
s: 235 2.7.0 Accepted
c: MAIL FROM: <cheechiangk@gmail.com>\r\n
s: 250 2.1.0 OK m2-20020a170902db0200b001ea02c8412asm621438plx.119 - gsmtp
c: RCPT TO: <kangcheechiang@gmail.com>\r\n
s: 250 2.1.5 OK m2-20020a170902db0200b001ea02c8412asm621438plx.119 - gsmtp
c: RCPT TO: <cheechiang@live.com>\r\n
s: 250 2.1.5 OK m2-20020a170902db0200b001ea02c8412asm621438plx.119 - gsmtp
c: DATA\r\n
s: 354  Go ahead m2-20020a170902db0200b001ea02c8412asm621438plx.119 - gsmtp
c: From: cheechiangk@gmail.com\r\n
c: To: kangcheechiang@gmail.com\r\n
c: To: cheechiang@live.com\r\n

**Comment by jeremydumais** [comment]
This problem is fixed in version 1.1.8 that will be release later today.
To and Cc addressed now appears as a single line.
Ex:
c: To: kangcheechiang@gmail.com, cheechiang@live.com\r\n

Thank you,
