### ISSUE TITLE
Build the CPP SMTPClient library on Windows

### ISSUE THREAD

**Issue by JamesBremner** [jeremydumais/CPP-SMTPClient-library#8]
Looking at the instructions here

https://github.com/jeremydumais/CPP-SMTPClient-library/wiki/Build-the-CPP-SMTPClient-library-on-Windows

> When building CPP-SMTPClient-library as a standalone project, the typical workflow starts with:
> 
> mkdir build
> cd build

There is a simple step ommitted - 

```
cd "installation folder"
mkdir build
cd build
```

**Comment by JamesBremner** [comment]
It looks like I also need to set OPENSSL_ROOT_DIR

`set OPENSSL_ROOT_DIR=C:\Users\James\code\ext\openssl`

Note that there can be NO spaces in this command

**Comment by JamesBremner** [comment]
It now fails with "googletest"

```
  Checking Build System
  Performing download step (git clone) for 'googletest'
  Cloning into 'googletest-src'...
  fatal: invalid reference: master
  CMake Error at googletest-download/googletest-prefix/tmp/googletest-gitclone.cmake:40 (message):
    Failed to checkout tag: 'master'
```

**Comment by JamesBremner** [comment]
Do I need "googletest"  Sounds like it should be possible to continue without this.

**Comment by JamesBremner** [comment]
[CMakeError.log](https://github.com/jeremydumais/CPP-SMTPClient-library/files/7590201/CMakeError.log)
[CMakeOutput.log](https://github.com/jeremydumais/CPP-SMTPClient-library/files/7590202/CMakeOutput.log)

**Comment by jeremydumais** [comment]
Thank you for the feedback James. The Build the CPP SMTPClient library on Windows documentation has been updated with your suggestions. GoogleTest is also optional now. The CMake option BUILD_TESTING is off by default.

Regards,
Jeremy
