### ISSUE TITLE
Error Code -58 "Unable to get local issuer certificate"

### ISSUE THREAD

**Issue by DctrNoob** [jeremydumais/CPP-SMTPClient-library#9]
So I compiled the opportunistic test app and linked it to my own build of LibreSSL under macOS. When running the test, I receive the error code -58 and message "unable to get local issuer certificate".

I then replaced LibreSSL with my own build of OpenSSL 1.1.1m and got the same result.

Any idea what that might be about?

**Comment by jeremydumais** [comment]
Hi, I will try to replicate the issue on my side and will let you know the result.

Regards,
Jeremy

**Comment by jeremydumais** [comment]
Hi,

Ok I've been able to reproduced the problem on macOS Catalina (version 10.15).

The thing is that OSX doesn't manage CA certificates like Linux. You need to export Systems Roots certificates from the Keychain Access.

So here's my workaround:

1. Get the OpenSSL directory by typing the command openssl version -d in a terminal. On my system it returns : /usr/local/ssl 

2. List the certs folder of the OpenSSL directory and it should be empty.
Ex: ls -la /usr/local/ssl/certs

3. Export all System Roots certificates to your certs folder. Ex: /usr/local/ssl/certs/certificates.pem
Note : You can follow the steps in the Keychain Access at http://movingpackets.net/2015/03/18/telling-openssl-about-your-root-certificates/
4.Add the 2 following environment variables to inform OpenSSL where you CA certificates are :

-     export SSL_CERT_FILE=/usr/local/ssl/certs/certificates.pem

-     export REQUESTS_CA_BUNDLE=/usr/local/ssl/certs/certificates.pem

Afters those steps, the CPP-SMTPClient-Library is working well on OSX.

Let me know if it's working on your side.
